create table ROLE (
    CODE        VARCHAR(16)  NOT NULL PRIMARY KEY,
    NAME        VARCHAR(30)  NOT NULL,
    RESTRICTED  CHAR(1)      NOT NULL,
    DESCRIPTION VARCHAR(200) NOT NULL
);

create table SERVICE (
    CODE        VARCHAR(16)  NOT NULL PRIMARY KEY,
    NAME        VARCHAR(80)  NOT NULL,
    URI         VARCHAR(100) NOT NULL,
    STOPPED     CHAR(1)      NOT NULL,
    GRANTEDTYPE INTEGER      NOT NULL,
    DESCRIPTION VARCHAR(200) NOT NULL
);

create table AUTHORITY (
    ROLECODE    VARCHAR(16) NOT NULL,
    SERVICECODE VARCHAR(16) NOT NULL
);

CREATE TABLE MEMBER 
(
	ID VARCHAR(10) NOT NULL,
	PASSWORD VARCHAR(20) NOT NULL,
	NAME VARCHAR(20) NOT NULL,
	EMAIL VARCHAR(80) NOT NULL,
	MODEL VARCHAR(30),
	ADDRESS VARCHAR(100),
	PHONE VARCHAR(20),
	ROLECODE VARCHAR(16) NOT NULL,
	primary key (ID)
);
